SITE = "https://kutech.it"

ORG_DESC = ("KU Tech, LLC is a customer-focused managed IT services company providing 24/7/365 support, "
            "cybersecurity, cloud solutions, datacenter services and AI-powered monitoring, so businesses "
            "can concentrate on their core work.")

# key, slug, name (H1 / nav), short (index blurb), meta_title, meta_desc, intro (answer-first),
# included, who, how, faqs [(q,a)], related keys, photo
SERVICES = [
 dict(key="managed", slug="managed-it-services", name="Managed IT services and 24/7/365 support",
  short="Help any hour of the day for your people, devices and systems.",
  meta_title="Managed IT Services & 24/7/365 IT Support | Ku Tech",
  meta_desc="24/7/365 managed IT services from Ku Tech: Level 1-3 support for servers, workstations, mobile devices, cloud and networks, with ticketing and remote help.",
  intro="Ku Tech's managed IT services act as your outsourced IT department. We provide 24/7/365 help desk support and Level 1-3 support for your Windows servers, workstations, mobile devices, cloud and networks, backed by a ticketing system and AI-powered monitoring, so problems are fixed fast and your team keeps working.",
  included=["Level 1-3 support for Windows servers, workstations, mobile devices, cloud and networks","Password resets and account help","A ticketing system that tracks every request","Remote connection for fast fixes","On-site support when it's needed","Patching and software updates","New staff setup and offboarding"],
  who="Businesses that don't have an IT department, or whose IT person is stretched too thin. If your team loses time to slow computers, password lockouts or software that won't cooperate, managed IT takes that burden away for one predictable monthly fee.",
  how="Every request goes into our ticketing system, so nothing gets lost and you can see what's happening. Most issues are solved remotely within minutes, and we come on site when needed. Behind the scenes, AI-powered monitoring watches your systems around the clock and fixes routine problems before anyone has to call.",
  faqs=[("Do you really offer support 24/7/365?","Yes. Ku Tech's help desk is available 24 hours a day, 365 days a year, including weekends and holidays."),
        ("What does Level 1-3 support mean?","Level 1 covers everyday requests like password resets. Level 2 handles deeper troubleshooting of devices and software. Level 3 covers complex server, network and cloud problems that need senior engineers. Ku Tech covers all three.")],
  related=["ai","cyber","equipment"], photo="help-desk"),
 dict(key="ai", slug="ai-it-monitoring", name="AI-powered IT monitoring and automation",
  short="Round-the-clock watch that fixes issues before they cause downtime.",
  meta_title="AI-Powered IT Monitoring & Automation | Ku Tech",
  meta_desc="Ku Tech's AI-powered monitoring watches your servers, devices, network and cloud around the clock and fixes routine IT issues before they cause downtime.",
  intro="Ku Tech uses AI-powered monitoring and automation to keep your business up and running. It watches your servers, devices, network and cloud accounts around the clock, spots warning signs early and fixes routine issues automatically, while our engineers handle anything that needs a human decision.",
  included=["Around-the-clock system monitoring","Predictive alerts before failures","Automated fixes for common issues","Performance and capacity tracking","Clear monthly health reports","Engineers on hand for anything complex"],
  who="Any business where downtime costs money: missed sales, idle staff or unhappy customers. It's especially valuable if you've been living with the break-fix cycle of calling someone only after something stops working.",
  how="Our monitoring detects unusual behavior, diagnoses the likely cause in seconds and runs proven fixes automatically, such as freeing disk space, restarting stuck services or re-running failed updates. Bigger issues go straight to a Ku Tech engineer with the full picture, and every incident teaches the system how to prevent the next one.",
  faqs=[("Does AI replace your engineers?","No. AI handles the constant watching and routine fixes. Ku Tech engineers review what it finds, make the decisions and handle anything complex."),
        ("Will I see what the monitoring finds?","Yes. You get clear reports on the health of your systems and what was fixed, in plain language.")],
  related=["managed","backup","strategy"], photo="monitoring"),
 dict(key="cyber", slug="cybersecurity-services", name="Cybersecurity and response management",
  short="Layered protection, continuous testing and a plan for when things go wrong.",
  meta_title="Cybersecurity Services & Incident Response | Ku Tech",
  meta_desc="Ku Tech cybersecurity: application and wireless security, continuous monitoring, testing and training, plus incident and disaster response and recovery.",
  intro="Ku Tech's cybersecurity services protect small and mid-sized businesses with layered defenses that we keep testing and improving. We cover application security, wireless networks, endpoints and email, train your staff, monitor continuously and stand ready to respond and recover if an incident happens.",
  included=["Application security","Wireless network management","Continuous monitoring, testing and training","Incident and disaster response and recovery","Endpoint detection and response","Email and phishing protection","Multi-factor authentication","Vulnerability scans and dark web monitoring"],
  who="Every business that handles customer data, payments or sensitive files, which is nearly all of them. Attackers increasingly target smaller companies because they expect weaker defenses.",
  how="We start by finding your biggest risks, then put protections in place across devices, email, networks and applications. Continuous monitoring and regular testing keep those defenses current, security awareness training helps your team spot phishing, and a clear response plan means that if something does happen, we contain it and get you back to normal quickly.",
  faqs=[("Is my business too small to be a target?","No. Small and mid-sized businesses are frequent targets because attackers expect them to have fewer protections."),
        ("What happens if we are attacked?","Ku Tech's incident response contains the threat, restores affected systems from clean backups and helps you understand what happened and how to prevent it.")],
  related=["backup","compliance","mobile"], photo="security"),
 dict(key="cloud", slug="cloud-solutions", name="Cloud solutions and Microsoft 365",
  short="Assessment, migration and training for email, files and apps in the cloud.",
  meta_title="Cloud Solutions, Migration & Microsoft 365 | Ku Tech",
  meta_desc="Ku Tech cloud solutions: cloud assessment and analysis, migration planning and training, Microsoft 365, Google Workspace and cloud server management.",
  intro="Ku Tech helps businesses move to the cloud and get the most from it. We assess which systems belong in the cloud, plan and carry out the migration, train your team and manage Microsoft 365, Google Workspace and cloud servers from then on, so you can work securely from anywhere.",
  included=["Cloud assessment and analysis","Migration planning and training","Microsoft 365 and Google Workspace","Azure and cloud server management","File sharing and collaboration","License management"],
  who="Businesses with aging on-site servers, teams that work from several locations, or anyone paying for cloud licenses they don't fully use.",
  how="We begin with a cloud assessment that weighs cost, security and performance. Then we plan the migration around your schedule to avoid downtime, move your email, files and applications, and train your people on the new tools. After the move, we manage accounts, licenses and security settings as part of your plan.",
  faqs=[("Will moving to the cloud disrupt my business?","Migrations are planned around your operations and are usually done outside business hours, so your team can keep working."),
        ("Can you help us use Microsoft 365 better?","Yes. Many businesses pay for Microsoft 365 features they never set up. We configure and train your team on the tools that fit how you work.")],
  related=["backup","mobile","projects"], photo="cloud"),
 dict(key="backup", slug="backup-disaster-recovery", name="Backup and disaster recovery",
  short="Tested backups and a plan to get you back online fast.",
  meta_title="Backup & Disaster Recovery Services | Ku Tech",
  meta_desc="Protect your data with Ku Tech backup and disaster recovery: encrypted backups, Microsoft 365 backup, regular restore testing and continuity planning.",
  intro="Ku Tech's backup and disaster recovery service makes sure your data is always protected and can be restored when it matters. We run automated, encrypted backups, back up Microsoft 365, test restores regularly and build a continuity plan so your business can recover quickly from hardware failure, mistakes or cyberattacks.",
  included=["Automated, encrypted backups","Microsoft 365 backup","Regular restore testing","Business continuity planning"],
  who="Any business that couldn't afford to lose its files, email or customer records, or to be offline for days while systems are rebuilt.",
  how="Backups run automatically and are monitored so a failed job is caught and re-run right away. We regularly test restores to prove your data can actually come back, and we document a recovery plan that sets out what gets restored first and how quickly.",
  faqs=[("Doesn't Microsoft 365 already back up my data?","Microsoft keeps its service running, but it's your responsibility to protect your data against deletion, ransomware and mistakes. A separate Microsoft 365 backup covers that gap."),
        ("How do I know my backups work?","Ku Tech tests restores on a regular schedule and reports the results, so you're not relying on hope.")],
  related=["cyber","cloud","ai"], photo="server-rack"),
 dict(key="datacenter", slug="datacenter-infrastructure", name="Datacenter and infrastructure services",
  short="Assessments, installations and the equipment that keeps you connected.",
  meta_title="Datacenter & Network Infrastructure Services | Ku Tech",
  meta_desc="Ku Tech datacenter services: infrastructure assessments, networking, server, storage and UPS installations, business Wi-Fi, firewalls and VoIP.",
  intro="Ku Tech designs, installs and maintains the infrastructure your business runs on. We start with infrastructure and architecture assessments, then handle networking, server, storage and UPS installations, business-grade Wi-Fi, firewalls, secure remote access and phone systems, so your office stays fast, secure and connected.",
  included=["Infrastructure and architecture assessments","Networking, server, storage and UPS installations","Business-grade Wi-Fi","Firewalls, switches and cabling","Secure remote access (VPN)","Business phone systems (VoIP)","Office moves and new sites"],
  who="Businesses with slow or unreliable networks, aging servers, a new office to fit out, or a server room that has grown without a plan.",
  how="An infrastructure assessment shows what you have, what's at risk and what to improve. We then design the right architecture, install and configure the equipment, document everything, and add it to our monitoring so it stays healthy.",
  faqs=[("What is a UPS and do I need one?","A UPS (uninterruptible power supply) keeps servers and network equipment running through short power cuts and lets them shut down safely in longer ones. Most businesses with on-site servers need one."),
        ("Can you help with an office move?","Yes. We plan and install networking, Wi-Fi, phones and equipment at the new site so your team is ready to work on day one.")],
  related=["equipment","projects","carrier"], photo="technician"),
 dict(key="equipment", slug="it-equipment-management", name="IT equipment management",
  short="Buying, tracking and deploying the right hardware.",
  meta_title="IT Equipment Purchasing & Asset Management | Ku Tech",
  meta_desc="Ku Tech IT equipment management: equipment purchasing and support, asset tracking, deployment analysis and process, and vendor management.",
  intro="Ku Tech's IT equipment management makes sure the right hardware is in the right hands. We handle equipment purchasing and support, track every device, analyze and streamline how new equipment is deployed, and manage vendors, so you spend less time on hardware and less money on the wrong gear.",
  included=["Equipment purchasing and support","Asset tracking","Deployment analysis and process","Vendor management"],
  who="Growing businesses that buy computers and devices regularly, or anyone who isn't sure what equipment they own, where it is or when it's due for replacement.",
  how="We recommend and buy equipment that fits your needs and budget, set it up to your standards and track it from purchase to retirement. A defined deployment process means new hires get working devices on day one, and we deal with vendors and warranties for you.",
  faqs=[("Can you buy equipment for us?","Yes. Ku Tech sources and purchases equipment on your behalf, then configures it before it reaches your staff."),
        ("Why does asset tracking matter?","Knowing what you own helps you plan replacements, control costs and keep lost or old devices from becoming security risks.")],
  related=["managed","mobile","datacenter"], photo="team"),
 dict(key="mobile", slug="mobile-workforce-management", name="Mobile workforce management",
  short="Secure, productive teams wherever they work.",
  meta_title="Mobile Workforce Management & Device Security | Ku Tech",
  meta_desc="Ku Tech mobile workforce management: provider analysis and migration support, plus device and endpoint security for staff at home and on the road.",
  intro="Ku Tech's mobile workforce management keeps teams secure and productive wherever they work. We analyze your mobile providers and support migrations, set up and manage phones and laptops, and secure every device and endpoint so company data stays protected at home, on the road and in the office.",
  included=["Provider analysis and migration support","Device and endpoint security for mobile staff","Mobile device setup and management","Secure access to company data on the go"],
  who="Businesses with remote or hybrid staff, field teams, or employees who use phones and laptops to reach company email and files.",
  how="We review your mobile plans and providers to find the best fit, then manage devices centrally so they're set up consistently, kept updated and protected. If a device is lost or stolen, company data can be locked or wiped remotely.",
  faqs=[("Can you secure personal phones that staff use for work?","Yes. Mobile device management can protect company email and files on personal devices without touching personal data."),
        ("Can you help us switch mobile providers?","Yes. We compare providers and plans and support the migration so your team stays connected.")],
  related=["cyber","carrier","equipment"], photo="business-owners"),
 dict(key="strategy", slug="it-strategy-technology-reviews", name="Technology reviews and IT strategy",
  short="Audits, expert recommendations and a roadmap that fits your budget.",
  meta_title="Technology Reviews, IT Audits & IT Strategy | Ku Tech",
  meta_desc="Ku Tech technology reviews: thorough IT audits, expert recommendations and implementation, roadmaps, budgeting and virtual CIO guidance.",
  intro="Ku Tech's technology reviews give you a clear picture of your IT and a plan to improve it. We conduct thorough technology audits to find optimization opportunities, recommend the most efficient solutions for your business, help implement them, and keep a roadmap and budget that match where your company is headed.",
  included=["Thorough technology audits","Expert recommendations and implementation","Technology roadmaps","IT budgeting and forecasting","Quarterly business reviews","Practical AI adoption for your team","Virtual CIO guidance","Co-managed IT for in-house teams"],
  who="Leaders who want technology to support growth instead of reacting to problems, and businesses planning a big change such as expansion, new systems or adopting AI tools.",
  how="We audit your systems, security, licenses and spending, then turn the findings into prioritized, practical recommendations. Regular business reviews keep the roadmap current, and our virtual CIO guidance gives you senior-level technology advice without a full-time hire.",
  faqs=[("What is a virtual CIO?","A virtual CIO provides strategic technology leadership, such as planning, budgeting and vendor decisions, on a part-time basis as part of your Ku Tech plan."),
        ("Can you help us adopt AI tools?","Yes. We help you choose AI tools that fit your business, set them up securely and train your team to use them well.")],
  related=["projects","ai","compliance"], photo="team"),
 dict(key="projects", slug="it-project-management", name="IT project management and execution",
  short="Smooth technology rollouts, coordinated end to end.",
  meta_title="IT Project Management & Technology Rollouts | Ku Tech",
  meta_desc="Ku Tech IT project management delivers end-to-end coordination for technology rollouts, with project timelines customized to your operational needs.",
  intro="Ku Tech's IT project management delivers end-to-end coordination so technology rollouts go smoothly. We plan every step, customize timelines around your operations, keep everyone informed and test thoroughly before handover, whether you're moving to the cloud, relocating an office or rolling out new systems.",
  included=["End-to-end project coordination","Timelines customized to your operations","Clear communication at every stage","Testing and handover to your team"],
  who="Businesses taking on a one-time technology change, such as a cloud migration, office move, new software rollout or infrastructure upgrade, with or without an ongoing managed IT plan.",
  how="We agree the scope, timeline and success measures up front, schedule disruptive work around your operations, coordinate vendors and carriers, and keep you updated throughout. Before handover, we test everything and make sure your team knows how to use it.",
  faqs=[("Do we need a managed IT plan to hire you for a project?","No. Ku Tech takes on individual projects as well as ongoing managed services."),
        ("How do you keep projects from disrupting work?","Timelines are built around your operations, and disruptive steps are scheduled for quieter times whenever possible.")],
  related=["cloud","datacenter","strategy"], photo="technician"),
 dict(key="carrier", slug="carrier-services", name="Carrier services analysis and partnerships",
  short="The right internet, phone and data providers at the right price.",
  meta_title="Carrier Services Analysis: Internet & Phone | Ku Tech",
  meta_desc="Ku Tech reviews your internet, phone and data services, compares providers through our carrier partnerships and supports you when switching.",
  intro="Ku Tech's carrier services analysis helps you get the right internet, phone and data services at the right price. We review what you have, compare options through our carrier partnerships, recommend the best fit for your needs and budget, and support you through any change of provider.",
  included=["Review of your current carrier services","Provider comparisons and recommendations","Access to our carrier partnerships","Support when changing providers"],
  who="Businesses with multiple or outdated carrier contracts, rising bills, unreliable internet, or a move to a new location.",
  how="We gather your current contracts and usage, identify waste and gaps, and compare providers on reliability, speed and cost. Once you choose, we coordinate the switch so your connections stay up.",
  faqs=[("Can you lower our internet and phone bills?","Often, yes. Many businesses pay for services they don't use or are on outdated plans. A carrier review shows where you can save."),
        ("Will switching carriers cause downtime?","We plan and coordinate changes carefully to keep disruption to a minimum.")],
  related=["datacenter","mobile","projects"], photo="hero-network"),
 dict(key="compliance", slug="it-compliance", name="IT compliance support",
  short="Controls and documentation to help you meet industry requirements.",
  meta_title="IT Compliance Support: HIPAA, PCI DSS & More | Ku Tech",
  meta_desc="Ku Tech IT compliance support for HIPAA, PCI DSS and more: security controls, policies and documentation, risk assessments and cyber insurance readiness.",
  intro="Ku Tech's IT compliance support helps businesses meet the data rules of their industry. We help you put the right security controls in place for frameworks such as HIPAA and PCI DSS, write the policies and documentation to prove it, run risk assessments and prepare for cyber insurance requirements.",
  included=["HIPAA, PCI DSS and similar frameworks","Security policies and documentation","Risk assessments","Cyber insurance readiness"],
  who="Healthcare practices, businesses that take card payments, and any company facing client security questionnaires or cyber insurance applications.",
  how="We assess where you stand against the requirements that apply to you, close the gaps with practical controls, and keep documentation up to date so you're ready for audits, questionnaires and insurance renewals.",
  faqs=[("Can you make us compliant?","We help you implement and document the technical controls that frameworks require. Compliance also involves your own policies and practices, and we guide you through those."),
        ("Why do cyber insurers ask so many questions?","Insurers now require controls such as multi-factor authentication and tested backups. We help you meet those requirements and answer the application accurately.")],
  related=["cyber","backup","strategy"], photo="security"),
]
BYKEY = {s["key"]: s for s in SERVICES}
